# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character] # The name of the module we are configuring is "character"
success_symbol = "[‚ûú](bold green)" # The "success_symbol" segment is being set to "‚ûú" with the color "bold green"
error_symbol = "[‚úó](bold red) "
vicmd_symbol = "[Vim](fg:black bg:green) "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[python]
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'


[aws]
format = 'on [$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = 'bold yellow'

[aws.region_aliases]
ap-northeast-1 = 'tky'
us-east-1 = 'va'

[gcloud]
format = '[$symbol$account(\($region\)\($project\))]($style) '
symbol = 'Ô∏èüá¨Ô∏è '
detect_env_vars = ['CLOUDSDK_CORE_PROJECT', 'CLOUDSDK_COMPUTE_ZONE', 'CLOUDSDK_CONFIG']


[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "ane1"

[gcloud.project_aliases]
my-playground-415616 = "pg"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "
truncation_length = 8

[nix_shell]
format = ' [$symbol$state( \($name\))]($style) '
impure_msg = 'im'
